# Generated by Django 3.2 on 2021-04-30 20:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210501_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultdescription',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
